/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.analysis.api.fir.components;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link GenerateNewCompilerTests.kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("analysis/analysis-api/testData/components/typeParameter")
@TestDataPath("$PROJECT_ROOT")
public class FirTypeParameterTypeTestGenerated extends AbstractFirTypeParameterTypeTest {
    @Test
    public void testAllFilesPresentInTypeParameter() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("analysis/analysis-api/testData/components/typeParameter"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("reified_argumentInFunctionalType.kt")
    public void testReified_argumentInFunctionalType() throws Exception {
        runTest("analysis/analysis-api/testData/components/typeParameter/reified_argumentInFunctionalType.kt");
    }

    @Test
    @TestMetadata("reified_extensionReceiver.kt")
    public void testReified_extensionReceiver() throws Exception {
        runTest("analysis/analysis-api/testData/components/typeParameter/reified_extensionReceiver.kt");
    }

    @Test
    @TestMetadata("reified_returnType.kt")
    public void testReified_returnType() throws Exception {
        runTest("analysis/analysis-api/testData/components/typeParameter/reified_returnType.kt");
    }

    @Test
    @TestMetadata("reified_valueParameter.kt")
    public void testReified_valueParameter() throws Exception {
        runTest("analysis/analysis-api/testData/components/typeParameter/reified_valueParameter.kt");
    }

    @Test
    @TestMetadata("reified_valueParameter_vararg.kt")
    public void testReified_valueParameter_vararg() throws Exception {
        runTest("analysis/analysis-api/testData/components/typeParameter/reified_valueParameter_vararg.kt");
    }
}
